// Open Graph social-card URLs.
//
// Branded 1200×630 cards are pre-rendered and hosted on R2 under the `og/`
// prefix (generated by scripts in the OG pipeline; see the archive notes).
// Detail pages get a card that composites the work's cover / thinker's
// portrait / piece's hero image onto the brand canvas; the home and each
// section index get a cover-mosaic card. Everything else falls back to the
// home card.
//
// Cards exist only where a source image existed at generation time, so the
// per-entry helpers take a boolean guard and return `undefined` (→ default
// card) when there's nothing to show.

const OG_BASE = "https://archive.indianliberals.in/og";

/** The site-wide default card (cover mosaic + wordmark). */
export const OG_HOME = `${OG_BASE}/home.jpg`;

/** Section-index card, e.g. ogSection("periodicals"). */
export function ogSection(name: string): string {
  return `${OG_BASE}/${name}.jpg`;
}

/** Per-work card (og/w/<id>.jpg) — only when the work has a cover. */
export function ogWork(id: string, hasCover: boolean): string | undefined {
  return hasCover ? `${OG_BASE}/w/${id}.jpg` : undefined;
}

/** Per-thinker card (og/t/<id>.jpg) — only when the profile has a portrait. */
export function ogThinker(id: string, hasPortrait: boolean): string | undefined {
  return hasPortrait ? `${OG_BASE}/t/${id}.jpg` : undefined;
}

/** Per-musing card (og/m/<id>.jpg) — only when the musing has a hero image. */
export function ogMusing(id: string, hasHero: boolean): string | undefined {
  return hasHero ? `${OG_BASE}/m/${id}.jpg` : undefined;
}

/** Per-opinion card (og/o/<id>.jpg) — only when the opinion has a hero image. */
export function ogOpinion(id: string, hasHero: boolean): string | undefined {
  return hasHero ? `${OG_BASE}/o/${id}.jpg` : undefined;
}
