// The front page of archive.indianliberals.in, rendered from live figures.
//
// The page used to be a static object regenerated by hand from a snapshot,
// and it fell a year behind the archive it fronted (1,575 works on the page,
// 8,000 in the collection). It is now drawn here from two live sources:
//
//   - https://indianliberals.in/api/archive-stats.json, which the site
//     computes from its content on every deploy (works, pages, years, the
//     decade histogram, voices, languages, runs, people), and
//   - the bucket itself, for how many bytes the documents come to.
//
// Nobody updates it; it follows the content. The wording between the
// numbers is the only thing kept here.

const esc = (s) =>
  String(s ?? "").replace(/[&<>"']/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[c]);
const num = (n) => Number(n ?? 0).toLocaleString("en-IN");
const gb = (bytes) => (bytes / 1e9).toFixed(bytes >= 10e9 ? 0 : 1);

const CRANE = "https://indianliberals.in/brand/brand-mark-crane.png";

export function renderLanding(s, bucket) {
  const span = s.earliest && s.latest ? s.latest - s.earliest : null;
  const peak = Math.max(1, ...s.decades.map((d) => d.count));
  const langs = s.languages ?? [];
  const langList = langs.map((l) => l.name).join(", ");
  const langCounts = langs.map((l) => `${num(l.count)} ${esc(l.name)}`).join("; ");
  const title = `The Indian Liberals Archive — ${num(s.works)} works${span ? `, ${span} years` : ""}`;
  const description = `A digitised archive of Indian liberal thought: ${num(s.works)} works, ${num(s.pages)} scanned pages${
    s.earliest ? `, ${s.earliest} to ${s.latest}` : ""
  }. ${(s.runs ?? []).slice(0, 4).map((r) => r.name).join(", ")} and more.`;

  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>${esc(title)}</title>
<meta name="description" content="${esc(description)}">
<link rel="canonical" href="https://archive.indianliberals.in/">
<meta property="og:type" content="website">
<meta property="og:url" content="https://archive.indianliberals.in/">
<meta property="og:title" content="The Indian Liberals Archive">
<meta property="og:description" content="${esc(`${num(s.works)} works · ${num(s.pages)} pages${span ? ` · ${span} years` : ""} of Indian liberal thought, digitised and open.`)}">
<meta property="og:image" content="https://archive.indianliberals.in/og/archive.jpg">
<meta property="og:image:width" content="1200">
<meta property="og:image:height" content="630">
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:image" content="https://archive.indianliberals.in/og/archive.jpg">
<link rel="icon" href="${CRANE}">
<style>
:root{
 --ink:#17130f; --paper:#faf7f2; --muted:#6b6058; --rule:#e3dbd0; --raise:#fffdfa;
 --saffron:#a83a00; --flame:#e76709; --forest:#0d5117; --chip:#f1e9de;
}
@media (prefers-color-scheme:dark){
 :root{ --ink:#ece5da; --paper:#100e0c; --muted:#9a8f83; --rule:#2b2520; --raise:#171411;
        --saffron:#ffa371; --flame:#e76709; --forest:#77b779; --chip:#1e1a16; }
}
*{box-sizing:border-box}
html{-webkit-text-size-adjust:100%}
body{margin:0;background:var(--paper);color:var(--ink);overflow-x:clip;
 font-family:system-ui,-apple-system,"Segoe UI",Roboto,sans-serif;line-height:1.6;
 -webkit-font-smoothing:antialiased}
.wrap{max-width:1000px;margin:0 auto;padding:0 24px}
.tnum{font-variant-numeric:tabular-nums}
.eyebrow{font-family:ui-monospace,"SF Mono",Menlo,monospace;font-size:.6875rem;
 letter-spacing:.18em;text-transform:uppercase;color:var(--saffron);font-weight:600}
h1,h2,.fig b{font-family:Georgia,"Iowan Old Style",serif;font-weight:600;text-wrap:balance;margin:0}
a{color:var(--saffron)}
.tri{height:3px;background:linear-gradient(90deg,var(--flame),var(--rule) 52%,var(--forest))}
header{padding:56px 0 8px}
.mark{display:flex;align-items:center;gap:14px;margin-bottom:28px;text-decoration:none;color:inherit}
.mark img{width:44px;height:44px}
.mark span{font-family:Georgia,serif;font-weight:600;font-size:1.0625rem;letter-spacing:-.01em}
h1{font-size:clamp(2.1rem,6vw,3.9rem);line-height:1.04;letter-spacing:-.025em;max-width:15ch}
.lede{color:var(--muted);font-size:1.0625rem;max-width:60ch;margin-top:18px}
.figs{display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:1px;
 background:var(--rule);border-block:1px solid var(--rule);margin:52px 0 0}
.fig{background:var(--paper);padding:26px 22px}
.fig b{display:block;font-size:clamp(2.4rem,7vw,3.5rem);line-height:1;letter-spacing:-.03em;
 font-variant-numeric:tabular-nums}
.fig i{display:block;font-style:normal;font-family:ui-monospace,Menlo,monospace;font-size:.6875rem;
 letter-spacing:.14em;text-transform:uppercase;color:var(--muted);margin-top:10px;font-weight:600}
.fig em{display:block;font-style:normal;color:var(--muted);font-size:.875rem;margin-top:6px}
section{padding:56px 0;border-bottom:1px solid var(--rule)}
.shead{display:flex;flex-direction:column;gap:9px;margin-bottom:30px}
h2{font-size:1.5rem;letter-spacing:-.015em}
.shead p{margin:0;color:var(--muted);max-width:62ch}
.hist{display:flex;gap:6px;align-items:flex-end;overflow-x:auto;padding-bottom:4px}
.bar{flex:1 1 0;min-width:52px;display:flex;flex-direction:column;align-items:center;gap:8px}
.col{width:100%;height:190px;display:flex;align-items:flex-end;background:var(--chip);border-radius:3px 3px 0 0}
.col span{display:block;width:100%;background:linear-gradient(180deg,var(--flame),var(--saffron));border-radius:3px 3px 0 0;
 transform-origin:bottom;animation:grow .9s cubic-bezier(.2,.7,.2,1) both;animation-play-state:paused}
@keyframes grow{from{transform:scaleY(0)}to{transform:scaleY(1)}}
.bar b{font-size:.8125rem}
.bar i{font-style:normal;font-family:ui-monospace,Menlo,monospace;font-size:.6875rem;color:var(--muted);letter-spacing:.06em}
.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(260px,1fr));gap:18px}
.card{background:var(--raise);border:1px solid var(--rule);border-radius:10px;padding:22px}
.card h3{margin:0 0 10px;font-size:.6875rem;font-family:ui-monospace,Menlo,monospace;letter-spacing:.14em;text-transform:uppercase;color:var(--muted);font-weight:600}
.card p{margin:0}
.card .big{display:block;font-family:Georgia,serif;font-size:2rem;line-height:1.1;letter-spacing:-.02em;margin-bottom:6px}
.card small{display:block;color:var(--muted);margin-top:10px;font-size:.8125rem;line-height:1.5}
.card ul{list-style:none;margin:0;padding:0}
.card li{display:flex;justify-content:space-between;gap:12px;padding:7px 0;border-bottom:1px solid var(--rule);font-size:.9375rem}
.card li:last-child{border-bottom:0}
.card li b{font-weight:600}
.cta{margin:56px 0 40px;display:flex;flex-direction:column;align-items:flex-start;gap:12px}
.btn{display:inline-block;background:var(--ink);color:var(--paper);text-decoration:none;padding:13px 22px;border-radius:999px;font-weight:600}
.cta p{margin:0;color:var(--muted)}
footer{padding:26px 0 48px;border-top:1px solid var(--rule);color:var(--muted);font-size:.8125rem}
</style>
</head>
<body>
<span class="tri" aria-hidden="true"></span>
<div class="wrap">
<header>
 <a class="mark" href="https://indianliberals.in/"><img src="${CRANE}" alt="" width="44" height="44"><span>Indian Liberals</span></a>
 <p class="eyebrow">The archive</p>
 <h1>${span ? `${span} years` : "Two centuries"} of Indian liberal thought, scanned.</h1>
 <p class="lede">This is the file store behind indianliberals.in: the pamphlets, journals, budget
  speeches, party papers and movement records of India&rsquo;s liberal tradition, digitised page by page and served
  openly. Every document here has a permanent address.</p>
</header>
</div>

<div class="wrap"><div class="figs">
 <div class="fig"><b class="tnum">${num(s.works)}</b><i>Works</i><em>Books, pamphlets, speeches, letters, journal issues</em></div>
 <div class="fig"><b class="tnum">${num(s.pages)}</b><i>Pages scanned</i><em>Median ${num(s.median_pages)} per document</em></div>
 <div class="fig"><b class="tnum">${bucket ? gb(bucket.pdfBytes) : "&mdash;"}<span style="font-size:.42em"> GB</span></b><i>Of documents</i><em>${num(s.pdfs)} PDFs, plus ${num(s.covers)} covers</em></div>
 <div class="fig"><b class="tnum">${s.earliest ?? "&mdash;"}</b><i>Earliest work</i><em>Running through to ${s.latest ?? "today"}</em></div>
</div></div>

<div class="wrap">
<section>
 <div class="shead"><p class="eyebrow">Distribution</p><h2>When the archive speaks</h2>
  <p>Works by decade of publication. The 1950s&ndash;70s peak is the licence-permit era, when the
   case for markets had to be argued hardest and most often.</p></div>
 <div class="hist">${s.decades
   .map(
     (d) =>
       `<div class="bar"><div class="col"><span style="height:${Math.max(2, Math.round((d.count / peak) * 100))}%"></span></div><b class="tnum">${num(d.count)}</b><i>${d.decade}s</i></div>`,
   )
   .join("")}</div>
</section>

<section>
 <div class="shead"><p class="eyebrow">Trivia</p><h2>Odds and ends</h2></div>
 <div class="grid">
  <div class="card"><h3>Oldest thing here</h3>
   <p><span class="big">${s.earliest ?? ""}</span>${esc(s.earliest_work?.title ?? "")}${
     s.earliest_work?.translation ? ` <span style="color:var(--muted)">(${esc(s.earliest_work.translation)})</span>` : ""
   }</p>
   <small>The newest material runs to ${s.latest ?? "today"}${span ? `: a ${span}-year span in one collection.` : "."}</small></div>
  <div class="card"><h3>Longest single work</h3>
   <p><span class="big tnum">${num(s.longest?.pages)} pages</span>${esc(s.longest?.title ?? "")}</p>
   <small>Most documents are far shorter: the median is ${num(s.median_pages)} pages, because the pamphlet and the letter were this
    tradition&rsquo;s natural units.</small></div>
  <div class="card"><h3>Most-published voices</h3><ul>${(s.voices ?? [])
    .map((v) => `<li><span>${esc(v.name)}</span><b class="tnum">${num(v.count)}</b></li>`)
    .join("")}</ul></div>
  <div class="card"><h3>Languages</h3>
   <p><span class="big tnum">${langs.length}</span>${esc(langList)}.</p>
   <small>${langCounts} — counted by the language of the document itself, with native-script titles catalogued as printed.</small></div>
  <div class="card"><h3>Largest runs</h3><ul>${(s.runs ?? [])
    .map((r) => `<li><span>${esc(r.name)}</span><b class="tnum">${num(r.count)}</b></li>`)
    .join("")}</ul></div>
  <div class="card"><h3>People and institutions</h3>
   <p><span class="big tnum">${num(s.thinkers)}</span>thinkers profiled, across ${num(s.organisations)} organisations.</p>
   <small>Plus ${num(s.musings)} curated excerpts and ${num(s.opinions)} essays on the main site.</small></div>
 </div>
</section>
</div>

<div class="wrap">
<div class="cta">
 <a class="btn" href="https://indianliberals.in/">Explore the archive &rarr;</a>
 <p>Search, read and cite every document at indianliberals.in</p>
</div>
<footer>Documents are reproduced for archival access; rights remain with their original
 publishers. Takedown on request. Figures measured from the collection at ${esc(new Date(s.generated_at).toUTCString())}.</footer>
</div>
<script>
(function(){
 var m=document.querySelectorAll('.col span');
 if(!('IntersectionObserver' in window))return;
 var io=new IntersectionObserver(function(es){es.forEach(function(e){
   if(e.isIntersecting){e.target.style.animationPlayState='running';io.unobserve(e.target);}});});
 m.forEach(function(el){io.observe(el);});
})();
</script>
</body>
</html>`;
}
