#!/usr/bin/env python3
"""Insert a `## Key points` digest into primary-work bodies that lack one.

Context
-------
Primary-work markdown bodies follow one of two conventions:

  Summary > Key points   (681 works) — single-piece works: speech, pamphlet,
                                       essay, book. The bullets ARE the digest.
  Summary > Essays       (781 works) — multi-article works: periodical issues
                                       and edited volumes. Per-article `### `
                                       sections carry the detail.

The second shape has no scannable whole-item digest: a reader landing on a 1960
Indian Libertarian issue gets prose plus a dozen article sections and no
takeaways. This script adds the missing digest layer WITHOUT disturbing the
per-article sections, placing it between Summary and Essays so the page reads
digest-then-detail.

Bullets are supplied by `--input` (generated by Sonnet subagents from each
record's existing summary/body; no new research, no outside facts).

Idempotent: a body that already has a `## Key points` heading is left alone.
Only the body is touched; frontmatter is never parsed or rewritten.
"""

import argparse
import json
import os
import re
import sys

FRONTMATTER = re.compile(r"^(---\n.*?\n---\n)(.*)$", re.S)


def render_bullets(bullets):
    """Match the archive's existing formatting: blank line between bullets."""
    return "## Key points\n\n" + "\n\n".join(f"- {b.strip()}" for b in bullets) + "\n"


def splice(body, block):
    """Insert `block` after the Summary section.

    Before `## Essays` when present (digest above per-article detail),
    otherwise appended at the end of the body.
    """
    m = re.search(r"^##\s+Essays\s*$", body, re.M)
    if m:
        head = body[: m.start()].rstrip("\n")
        tail = body[m.start() :]
        return f"{head}\n\n{block}\n{tail}"
    return body.rstrip("\n") + "\n\n" + block


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--input", required=True, help="JSON: [{id, key_points[]}]")
    ap.add_argument("--content-dir", default="apps/site/src/content/primary-works")
    ap.add_argument("--apply", action="store_true", help="write files (default: dry run)")
    ap.add_argument("--limit", type=int, default=0)
    args = ap.parse_args()

    records = json.load(open(args.input, encoding="utf-8"))
    if args.limit:
        records = records[: args.limit]

    changed = skipped_existing = missing_file = no_bullets = 0
    for rec in records:
        rid, bullets = rec.get("id"), rec.get("key_points") or []
        path = os.path.join(args.content_dir, rid + ".md")
        if not os.path.exists(path):
            print(f"MISSING FILE  {rid}", file=sys.stderr)
            missing_file += 1
            continue
        if not bullets:
            print(f"NO BULLETS    {rid}", file=sys.stderr)
            no_bullets += 1
            continue

        text = open(path, encoding="utf-8").read()
        m = FRONTMATTER.match(text)
        if not m:
            print(f"NO FRONTMATTER {rid}", file=sys.stderr)
            missing_file += 1
            continue
        fm, body = m.group(1), m.group(2)

        if re.search(r"^##\s+Key points\s*$", body, re.M):
            skipped_existing += 1
            continue

        new_body = splice(body, render_bullets(bullets))
        if args.apply:
            with open(path, "w", encoding="utf-8") as fh:
                fh.write(fm + new_body)
        changed += 1

    verb = "wrote" if args.apply else "would write"
    print(
        f"{verb}: {changed} | already had Key points: {skipped_existing} | "
        f"no bullets: {no_bullets} | unusable: {missing_file}"
    )
    if not args.apply:
        print("(dry run — pass --apply to write)")


if __name__ == "__main__":
    main()
