#!/usr/bin/env python3
"""
Step 6: emit data/classify/coverage-report.md with per-collection
coverage metrics, top proposed_themes, and remediation queues.

Run:
    .venv-extract/bin/python3 scripts/synthesis/audit-classify-coverage.py
    .venv-extract/bin/python3 scripts/synthesis/audit-classify-coverage.py --test
"""
from __future__ import annotations

import argparse
import re
import sys
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
CONTENT_ROOT = ROOT / "apps/site/src/content"
OUT = ROOT / "data/classify/coverage-report.md"

_FRONTMATTER_RX = re.compile(r"^---\n(.*?)\n---", re.S)


def _parse_yaml_list_items(block: str) -> list[str]:
    """Parse the body of a YAML list (after the `key:` line), accepting both
    quoted (`- "foo"`) and unquoted (`- foo`) forms. Stops at non-list lines
    (the caller is responsible for slicing to the relevant block)."""
    items: list[str] = []
    for line in block.splitlines():
        sub = re.match(r'\s*-\s*"([^"]+)"\s*$', line)
        if sub:
            items.append(sub.group(1))
            continue
        sub = re.match(r'\s*-\s*([^"\s].*?)\s*$', line)
        if sub:
            items.append(sub.group(1))
    return items


def parse_fields(md: Path) -> dict:
    text = md.read_text(encoding="utf-8")
    m = _FRONTMATTER_RX.match(text)
    if not m:
        return {}
    fm = m.group(1)
    out: dict = {"id": md.stem}

    def get_array(key: str) -> list[str]:
        # Preemptive regex fix: accept both quoted and unquoted list items.
        # The original plan's pattern only matched quoted items, which has
        # bitten us twice before on adjacent parsers.
        mm = re.search(
            rf"^{re.escape(key)}:\s*(\[\]|(?:\n[ \t]+-[^\n]+)+)",
            fm, re.M,
        )
        if not mm or mm.group(1).strip() == "[]":
            return []
        return _parse_yaml_list_items(mm.group(1))

    out["themes"] = get_array("themes")
    out["proposed_themes"] = get_array("proposed_themes")
    out["key_concepts"] = get_array("key_concepts")

    for single in ("pull_quote", "stance", "kind", "period_window", "source_channel"):
        mm = re.search(rf"^{re.escape(single)}:\s*(.+)$", fm, re.M)
        out[single] = mm.group(1).strip() if mm else None

    # geographic_scope.scale / places
    # NOTE: the trailing line may lack a `\n` because the frontmatter parser
    # strips it. Allow the final line to lack a newline so we don't drop the
    # last `- "place"` item when geographic_scope is the last frontmatter key.
    scope_block = re.search(
        r"^geographic_scope:\s*\n((?:[ \t]+.*(?:\n|$))+)",
        fm, re.M,
    )
    if scope_block:
        body = scope_block.group(1)
        ss = re.search(r"^[ \t]+scale:\s*(\S+)", body, re.M)
        out["scale"] = ss.group(1).strip() if ss else None
        # places parsed via the shared helper so unquoted forms also count.
        places_block = re.search(
            r"^[ \t]+places:\s*(\[\]|(?:\n[ \t]+-[^\n]+)+)",
            body, re.M,
        )
        if not places_block or places_block.group(1).strip() == "[]":
            out["places"] = []
        else:
            out["places"] = _parse_yaml_list_items(places_block.group(1))
    else:
        out["scale"] = None
        out["places"] = []
    return out


def coverage_pct(items: list[dict], pred) -> tuple[int, int]:
    n_match = sum(1 for it in items if pred(it))
    return n_match, len(items)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--test", action="store_true")
    args = parser.parse_args()
    if args.test:
        print("audit-classify-coverage has no built-in tests (output-shape only).")
        return 0

    per_coll: dict[str, list[dict]] = {}
    for coll in ("musings", "opinions"):
        per_coll[coll] = [parse_fields(md) for md in sorted((CONTENT_ROOT / coll).glob("*.md"))]

    lines: list[str] = ["# Classification Coverage Report", ""]
    lines.append(f"Generated by `audit-classify-coverage.py`.")
    lines.append("")

    proposed_global: Counter[str] = Counter()

    for coll, items in per_coll.items():
        if not items:
            continue
        n = len(items)
        lines.append(f"## {coll} ({n} entries)")
        lines.append("")
        lines.append("| Dimension | Populated | % |")
        lines.append("|---|---|---|")
        for key, pred in [
            ("themes (≥1)", lambda it: len(it["themes"]) > 0),
            ("kind", lambda it: it["kind"] is not None),
            ("stance", lambda it: it["stance"] is not None),
            ("period_window", lambda it: it["period_window"] is not None),
            ("key_concepts (≥1)", lambda it: len(it["key_concepts"]) > 0),
            ("pull_quote", lambda it: it["pull_quote"] not in (None, '""')),
            ("scale", lambda it: it["scale"] is not None),
        ]:
            m_n, _ = coverage_pct(items, pred)
            lines.append(f"| {key} | {m_n}/{n} | {m_n*100//n}% |")

        # Places for regional/bi-regional subset
        regional = [it for it in items if it["scale"] in ("regional", "bi-regional")]
        if regional:
            with_places = sum(1 for it in regional if it["places"])
            lines.append(f"| places (≥1, regional/bi-regional subset) | {with_places}/{len(regional)} | {with_places*100//len(regional)}% |")
        lines.append("")

        # Proposed themes per-collection top 15
        local_proposed: Counter[str] = Counter()
        for it in items:
            local_proposed.update(it["proposed_themes"])
            proposed_global.update(it["proposed_themes"])
        if local_proposed:
            lines.append(f"### Top proposed_themes in {coll}")
            lines.append("")
            for t, c in local_proposed.most_common(15):
                lines.append(f"- `{t}` ({c})")
            lines.append("")

    lines.append("## Global proposed_themes (curator review)")
    lines.append("")
    if proposed_global:
        for t, c in proposed_global.most_common(30):
            lines.append(f"- `{t}` ({c})")
    else:
        lines.append("(none)")
    lines.append("")
    lines.append(f"_Total unique proposed_themes: {len(proposed_global)}_")
    lines.append("")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines))
    print(f"wrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
