#!/usr/bin/env python3
"""
Emit data/synthesis/ner-input.jsonl — one entry per line for the
Phase B in-prose NER pass. Reads English entries from the four
in-scope collections (musings, opinions, theprint-mirror,
primary-works) and writes id + collection + title + body for each.

Filters applied:
  - language == "en" (the authority is English-name-keyed; non-English
    bodies don't resolve cleanly)
  - primary-works only: body has ≥200 chars of prose (excluding
    frontmatter and the structured key_points list). Per supplementary
    spec §6, this is the operational definition of "non-trivial summary".
  - primary-works only: needs_extraction != true

Run from repo root:
    python3 scripts/synthesis/prepare-ner-batches.py
"""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
CONTENT_ROOT = ROOT / "apps/site/src/content"
OUT = ROOT / "data/synthesis/ner-input.jsonl"

IN_SCOPE = ("musings", "opinions", "theprint-mirror", "primary-works")
MIN_BODY_CHARS = 200


def split_frontmatter(text: str) -> tuple[dict, str, str]:
    """Return (frontmatter_dict, frontmatter_text, body) for an MD file.

    The dict is a SHALLOW parse — only flat top-level string/bool/null
    keys. Nested keys (e.g., primary-works' `publication.language:`) are
    NOT recovered into the dict; callers that need nested values should
    grep the `frontmatter_text` field directly with a targeted regex.
    Two-pass design avoids reimplementing a full YAML parser."""
    m = re.match(r"^---\n(.*?)\n---\n?(.*)$", text, re.S)
    if not m:
        return {}, "", text
    fm_text, body = m.group(1), m.group(2)
    fm: dict = {}
    for line in fm_text.splitlines():
        # Skip indented lines (they belong to nested blocks)
        if line.startswith((" ", "\t")):
            continue
        km = re.match(r"^([a-zA-Z_][a-zA-Z0-9_]*)\s*:\s*(.*)$", line)
        if not km:
            continue
        key, val = km.group(1), km.group(2).strip()
        if val.startswith('"') and val.endswith('"'):
            val = val[1:-1]
        elif val.startswith("'") and val.endswith("'"):
            val = val[1:-1]
        if val == "true":
            fm[key] = True
        elif val == "false":
            fm[key] = False
        elif val in ("null", ""):
            fm[key] = None
        else:
            fm[key] = val
    return fm, fm_text, body


_NESTED_PUBLICATION_LANG_RX = re.compile(
    r"^publication:\s*\n(?:[ \t]+\w+:.*\n)*?[ \t]+language:\s*[\"']?([a-z]{2})[\"']?",
    re.M,
)


def language_for_entry(collection: str, fm_dict: dict, fm_text: str) -> str:
    """Return the language code for an entry. Primary-works store the
    language under `publication.language`; everything else uses the
    top-level `language:` field. Default 'en' if absent."""
    if collection == "primary-works":
        m = _NESTED_PUBLICATION_LANG_RX.search(fm_text)
        if m:
            return m.group(1)
        return "en"
    return fm_dict.get("language") or "en"


def primary_work_body_qualifies(body: str) -> bool:
    """For primary-works, the rendered body holds the AI-generated summary
    + a structured Key points block. We want NER to read the summary prose
    only — not the bullet list. Strip the '## Key points' section and
    trailing AI-provenance footer, then check we have ≥MIN_BODY_CHARS of
    prose."""
    # Strip the Key points list (everything from '## Key points' onwards)
    stripped = re.split(r"\n##\s+Key\s+points\b", body, maxsplit=1, flags=re.I)[0]
    # Strip the trailing 'Generated by the v1.5 extraction pipeline' footer
    stripped = re.split(r"\n\*Generated by", stripped, maxsplit=1)[0]
    # Collapse whitespace and count visible chars (drop markdown emphasis)
    plain = re.sub(r"[*_`>#]+", "", stripped)
    plain = re.sub(r"\s+", " ", plain).strip()
    return len(plain) >= MIN_BODY_CHARS


def main() -> int:
    OUT.parent.mkdir(parents=True, exist_ok=True)
    n_total = 0
    n_skipped_lang = 0
    n_skipped_thin = 0
    n_skipped_extract = 0
    n_emitted = 0
    with OUT.open("w", encoding="utf-8") as out_f:
        for collection in IN_SCOPE:
            cdir = CONTENT_ROOT / collection
            if not cdir.is_dir():
                print(f"[skip] {collection}: directory missing", file=sys.stderr)
                continue
            for md_path in sorted(cdir.glob("*.md")):
                n_total += 1
                text = md_path.read_text(encoding="utf-8")
                fm, fm_text, body = split_frontmatter(text)
                # Language filter — primary-works keep language nested
                # under publication.language; everything else uses
                # top-level language. Default 'en' if absent.
                lang = language_for_entry(collection, fm, fm_text)
                if lang != "en":
                    n_skipped_lang += 1
                    continue
                # Primary-works extra filters
                if collection == "primary-works":
                    if fm.get("needs_extraction") is True:
                        n_skipped_extract += 1
                        continue
                    if not primary_work_body_qualifies(body):
                        n_skipped_thin += 1
                        continue
                # Title
                title = fm.get("title") or md_path.stem
                # Emit
                rec = {
                    "id": md_path.stem,
                    "collection": collection,
                    "title": title,
                    "body": body.strip(),
                }
                out_f.write(json.dumps(rec, ensure_ascii=False) + "\n")
                n_emitted += 1

    print(json.dumps({
        "total_scanned": n_total,
        "emitted": n_emitted,
        "skipped_non_english": n_skipped_lang,
        "skipped_needs_extraction": n_skipped_extract,
        "skipped_thin_summary": n_skipped_thin,
        "output_path": str(OUT.relative_to(ROOT)),
    }, indent=2))
    return 0


if __name__ == "__main__":
    sys.exit(main())
