#!/usr/bin/env python3
"""Strip editorial/admin markers from MD bodies so the public UI is clean.
The frontmatter flags (needs_review, bio_source, needs_extraction) preserve
the same status info for the admin / Sveltia CMS view.

Patterns stripped:
  - "Generated by the v1.5 extraction pipeline. Awaiting editorial review."
  - "Generated by the v1.5 extraction pipeline (re-summarized…)."
  - "Entry created during the Phase A cross-link audit…" + follow-up para
  - "Entry pending editorial review." (thinker + org stub)
  - "Awaiting LLM extraction." + WordPress-DB-import explanation
  - "Sourced from the WordPress database export (post ID…)" footer
  - "(*Generated by …*)" inline italic footers
  - Standalone `---` separators that ONLY introduced one of the above
    (cleaned up so we don't leave dangling horizontal rules)

Idempotent — runs again with no effect once markers are stripped.
"""
import re
from pathlib import Path

ROOT = Path('/Users/siraj/Indian Liberals Website')
CONTENT = ROOT / 'apps/site/src/content'

# Patterns to strip, in order. Each entry is (regex, replacement).
# Most are stripped to '' (deleted); a couple replace with '' but preserve
# surrounding paragraph spacing.
PATTERNS = [
    # Primary-works v1.5 pipeline footer (any wording variant), with leading separator
    (re.compile(r'\n+\s*---\s*\n+\s*\*Generated by the v1\.5 extraction pipeline[^*]*\*\s*\n*', re.S), '\n'),
    # Bare-italic version without leading ---
    (re.compile(r'\n+\s*\*Generated by the v1\.5 extraction pipeline[^*]*\*\s*\n*', re.S), '\n'),

    # Phase A stub thinker placeholder
    (re.compile(
        r'\*Entry created during the Phase A cross-link audit[^*]*\*\s*\n+\s*'
        r'This thinker appeared as an author or subject in the corpus\.[^.]*\.\s*\n*', re.S
    ), ''),

    # Imported thinker placeholder (alt phrasing)
    (re.compile(
        r'\*Entry pending editorial review\. The AI extraction pipeline identified this person[^*]*\*\s*\n*\s*'
        r'(?:\*\*Provenance:\*\*[^\n]*\n)?', re.S
    ), ''),

    # Generic "Entry pending editorial review." (thinker stub bios + org stubs)
    (re.compile(r'\*Entry pending editorial review\.\*\s*\n*', re.S), ''),

    # Needs-extraction primary-works body
    (re.compile(
        r'_Awaiting LLM extraction\._\s*\n+'
        r'This entry was imported from the legacy WordPress database\.[\s\S]*?'
        r'(?:Until extraction runs, please refer to the staging PDF\s*\n*\(`pdf_staging_path` in the frontmatter\)\.\s*)?',
        re.S
    ), ''),

    # WordPress DB-export footer (musings/opinions/interviews/theprint-mirror)
    (re.compile(r'\n+\s*---\s*\n+\s*_Sourced from the WordPress database export[^_]*_\s*\n*', re.S), '\n'),
    (re.compile(r'\n+\s*_Sourced from the WordPress database export[^_]*_\s*\n*', re.S), '\n'),

    # Clean up any trailing dangling --- separators at the very end of the body
    (re.compile(r'\n+\s*---\s*\n*\s*$', re.S), '\n'),

    # Collapse 3+ blank lines into 2 (cosmetic)
    (re.compile(r'\n{4,}', re.S), '\n\n\n'),
]

def strip_file(p: Path) -> bool:
    text = p.read_text(encoding='utf-8')
    if not text.startswith('---\n'):
        return False
    fm_end = text.find('\n---\n', 4)
    if fm_end == -1:
        return False
    fm_text = text[:fm_end + 5]
    body = text[fm_end + 5:]
    new_body = body
    for rx, repl in PATTERNS:
        new_body = rx.sub(repl, new_body)
    if new_body == body:
        return False
    # Ensure body ends with one newline
    new_body = new_body.rstrip() + '\n' if new_body.strip() else '\n'
    p.write_text(fm_text + new_body, encoding='utf-8')
    return True


changed_by_collection = {}
for collection in ['musings', 'opinions', 'theprint-mirror', 'primary-works', 'interviews', 'thinkers', 'organisations']:
    cdir = CONTENT / collection
    if not cdir.exists():
        continue
    changed = 0
    for p in cdir.glob('*.md'):
        if strip_file(p):
            changed += 1
    changed_by_collection[collection] = changed

print('Markers stripped, files changed by collection:')
for coll, n in changed_by_collection.items():
    print(f'  {coll:<20s}  {n}')
print(f'\nTotal: {sum(changed_by_collection.values())}')
